<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="242328" started-at="2017-09-20T11:21:45Z" finished-at="2017-09-20T11:25:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="242328" started-at="2017-09-20T11:21:45Z" finished-at="2017-09-20T11:25:47Z">
      <class name="IncidentNearMiss.IncidentReportTest">
        <test-method status="PASS" signature="initialioseBrowser()[pri:0, instance:IncidentNearMiss.IncidentReportTest@2b5825fa]" name="initialioseBrowser" is-config="true" duration-ms="26868" started-at="2017-09-20T16:51:18Z" finished-at="2017-09-20T16:51:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialioseBrowser -->
        <test-method status="PASS" signature="beforeSu()[pri:0, instance:IncidentNearMiss.IncidentReportTest@2b5825fa]" name="beforeSu" is-config="true" duration-ms="95" started-at="2017-09-20T16:51:45Z" depends-on-methods="common_Function.WebDriverPass.initialioseBrowser" finished-at="2017-09-20T16:51:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSu -->
        <test-method status="FAIL" signature="IncidentReports()[pri:1, instance:IncidentNearMiss.IncidentReportTest@2b5825fa]" name="IncidentReports" duration-ms="242139" started-at="2017-09-20T16:51:45Z" finished-at="2017-09-20T16:55:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at IncidentNearMiss.IncidentReportTest.IncidentReports(IncidentReportTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- IncidentReports -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:IncidentNearMiss.IncidentReportTest@2b5825fa]" name="afterMethod" is-config="true" duration-ms="175" started-at="2017-09-20T16:55:47Z" finished-at="2017-09-20T16:55:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=IncidentReports status=FAILURE method=IncidentReportTest.IncidentReports()[pri:1, instance:IncidentNearMiss.IncidentReportTest@2b5825fa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterSu()[pri:0, instance:IncidentNearMiss.IncidentReportTest@2b5825fa]" name="afterSu" is-config="true" duration-ms="27" started-at="2017-09-20T16:55:47Z" finished-at="2017-09-20T16:55:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSu -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:IncidentNearMiss.IncidentReportTest@2b5825fa]" name="closeBrowser" is-config="true" duration-ms="761" started-at="2017-09-20T16:55:47Z" depends-on-methods="IncidentNearMiss.IncidentReportTest.afterSu" finished-at="2017-09-20T16:55:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- IncidentNearMiss.IncidentReportTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
